services:
  keycloak:
    image: guilhermelazy/keycloackroteiro:latest
    container_name: keycloak-prod
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - roteiro-network-prod

  mysql:
    image: mysql:latest
    container_name: roteirodb-prod
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=roteiro
      - MYSQL_USER=projeto
      - MYSQL_PASSWORD=12345
    command: --innodb-buffer-pool-size=64M --max-connections=50 --performance-schema=OFF
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - roteiro-network-prod

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roteiro-app-prod
    environment:
      - DB_USERNAME=projeto
      - DB_PASSWORD=12345
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/roteiro?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - CLIENT_ID=admin-cli
      - KC_ADMIN_NAME=guilherme.vieira.lazarotto@gmail.com
      - KC_ADMIN_PASSWORD=anderson
      - KEYCLOAK_URL=http://keycloak-prod:8080
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - keycloak
    networks:
      - roteiro-network-prod
    volumes:
      - ./uploads:/app/uploads


networks:
  roteiro-network-prod:
    driver: bridge

volumes:
  mysql_data_prod: