#Toncat sobe na 8080. Configuração para alterar a porta que irá subir.
server:
  port: 8081
  #servlet:
  #  contextPath: /api
upload:
  dir: uploads/

#CONFIGURAÇÃO BANCO NO CONTAINER LOCAL P/ COMANDO DA LINHA 32
spring:
#  profiles:
#    active: application-test
  datasource:
    url: jdbc:mysql://localhost:3307/roteiro?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: projeto
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
        show_sql: false
        format_sql: true
  mvc:
    static-path-pattern: /uploads/**


  #docker run --name roteirodb -p 3307:3306 -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=roteiro -e MYSQL_USER=projeto -e MYSQL_PASSWORD=12345 -d mysql:latest


  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
          jwk-set-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/certs


logging:
  level:
    ifpr:
      roteiropromo: debug
    web: debug

